debug: false
server:
  port: 8081

spring:
  datasource:
    sys:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
  application:
    admin:
      jmx-name: